on:
  push:
    branches:
      - 'main'

jobs:
  action_practice1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git
    - name: Checkout (practice_action)
      uses: actions/checkout@v4  # Use the latest version of actions/checkout
      with:
        repository: huiwangredhat/practice_action
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version
    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v3
      with:
        files: "controls.json"
    - name: check path
      run: |
        pwd
        ls
    - name: File exists
      id: controls
      if: steps.check_files.outputs.files_exists == 'true'
      uses: actions/upload-artifact@v4 # v4
      with:
        name: controls
        path: controls.json
    # Step 1: Checkout OSCAL content as the trestlebot lab
    - name: Checkout OSCAL content
      if: steps.check_files.outputs.files_exists == 'true'
      run: |
        git clone https://github.com/huiwangredhat/trestle-repo.git
        pwd
    - name: Checkout CaC 
      if: steps.check_files.outputs.files_exists == 'true'
      run: |
        git clone https://github.com/ComplianceAsCode/content.git
        pwd
      # Step 2: Checkout trestlebot
    - name: Checkout trestlebot
      uses: actions/checkout@v4  # Use the latest version of actions/checkout
      with:
        repository: complytime/trestle-bot
    - name: Setup trestlebot
      run: |
        ls
        pwd
        python3.9 -m pip install --no-cache-dir --upgrade pip setuptools
        python3.9 -m pip install --no-cache-dir "poetry==1.7.1"
        poetry install
    - name: Download artifact
      uses: actions/download-artifact@v4 #v4 
      with:
        name: controls
    - name: Sync catalog
      run: |
        CONTROLS=$(cat controls.json | jq -r '.controls[]')
        for control in $CONTROLS; do
          policy_id=$(echo "$control" | cut -f1 -d".")
          if [[ "$policy_id" == *"SRG-APP"* ]] || [[ "$policy_id" == *"SRG-OS"* ]]; then
            echo "Ignoring SRG-APP and SRG-OS: $policy_id"
          elif [[ "$policy_id" == *"section"* ]]; then
            echo "Section found, setting policy_id to 'cis_ocp_1_4_0'"
            policy_id="cis_ocp_1_4_0"
            poetry run trestlebot sync-cac-content catalog --dry-run --repo-path ../trestle-repo --committer-email test@redhat.com --committer-name test --branch main --cac-content-root ../content --policy-id $policy_id --oscal-catalog $policy_id
          else
            echo "Syncing catalog with policy_id: $policy_id"
            poetry run trestlebot --help
          fi
        done
        ls ../trestle-repo/catalogs