on:
  push:
    branches:
      - 'main'

jobs:
  action_practice1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git
    - name: Checkout (CTF)
      uses: actions/checkout@v4  # Use the latest version of actions/checkout
      with:
        repository: huiwangredhat/action_practice
        ref: filter_controls_update
        path: ctf
    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v3
      with:
        files: "existfile.txt"
    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      run: echo "It exists !"
